### PR TITLE
done with alert and button component

### PR DESCRIPTION
**Pull request by dev-prabhat**

### CODE REVIEW

**Comment by tonymike99** [comment]
Looks good to me!

**Review by iRohitGaur — APPROVED** [review]
Looks good 👍

**Review by sanu29 — APPROVED** [review]
Good and Clean code. Spacing can be improved in HTML file. Class names are meaningful and easy to remember. Min lines of CSS in each file which is good.. Also  reset is also defined and the way you have imported the fonts URL in CSS and not linked in HTML is Great.

I think you are good to go. 👍

**Comment by sudipkundu999** [comment]
Looks good.
Easy to read and understand.

**Review by sudipkundu999 — APPROVED** [review]

**Pull request merged**
